import { useEffect, useCallback } from "react";
import { colors, typography } from "../../lib/theme";
import { Button } from "../../components/ui/Button";

export function TermsOfService({ onClose }: { onClose: () => void }) {
  const handleKeyDown = useCallback((e: KeyboardEvent) => {
    if (e.key === "Escape") onClose();
  }, [onClose]);

  useEffect(() => {
    document.addEventListener("keydown", handleKeyDown);
    return () => document.removeEventListener("keydown", handleKeyDown);
  }, [handleKeyDown]);

  return (
    <div
      style={{
        position: "fixed", inset: 0, zIndex: 110,
        background: "rgba(0,0,0,0.6)", backdropFilter: "blur(8px)",
        display: "flex", alignItems: "center", justifyContent: "center",
      }}
      onClick={(e) => { if (e.target === e.currentTarget) onClose(); }}
    >
      <div style={{
        background: colors.bg.card, borderRadius: 14,
        border: `1px solid ${colors.border.default}`,
        boxShadow: "0 32px 64px rgba(0,0,0,0.5)",
        padding: "28px 32px", width: 560, maxHeight: "85vh",
        display: "flex", flexDirection: "column",
      }}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 20, flexShrink: 0 }}>
          <h2 style={{ ...typography.pageTitle, color: colors.text.primary }}>Terms of Service</h2>
          <button onClick={onClose} style={{
            width: 28, height: 28, borderRadius: 6, border: "none",
            background: colors.bg.hover, color: colors.text.muted,
            cursor: "pointer", fontSize: 16,
            display: "flex", alignItems: "center", justifyContent: "center",
          }}>&times;</button>
        </div>

        <div style={{ overflowY: "auto", flex: 1, paddingRight: 4, fontSize: 13, lineHeight: 1.7, color: colors.text.secondary }}>
          <p style={{ color: colors.text.muted, marginBottom: 16 }}>Last updated: April 2026</p>

          <Section title="License">
            <p>
              Narrator is open-source software released under the <strong style={{ color: colors.text.primary }}>MIT License</strong>. The source code is available on GitHub. You are free to use, modify, and distribute the software in accordance with the license terms.
            </p>
          </Section>

          <Section title="Disclaimer of Warranty">
            <p>
              Narrator is provided "as is", without warranty of any kind, express or implied. The authors and contributors are not liable for any claim, damages, or other liability arising from the use of the software. Use Narrator at your own risk.
            </p>
          </Section>

          <Section title="AI-Generated Content">
            <p>
              Narration scripts produced by Narrator are generated by third-party AI models (Anthropic Claude, OpenAI). AI-generated content may contain inaccuracies, errors, or inappropriate output. You are solely responsible for reviewing, editing, and verifying all generated content before use.
            </p>
          </Section>

          <Section title="API Keys & Third-Party Services">
            <p>
              Narrator requires API keys from third-party providers to function. By using Narrator with these services, you agree to their respective terms:
            </p>
            <ul style={{ paddingLeft: 20, marginTop: 8 }}>
              <li><strong style={{ color: colors.text.primary }}>Anthropic</strong> — anthropic.com/terms</li>
              <li><strong style={{ color: colors.text.primary }}>OpenAI</strong> — openai.com/terms</li>
              <li><strong style={{ color: colors.text.primary }}>ElevenLabs</strong> — elevenlabs.io/terms</li>
            </ul>
            <p style={{ marginTop: 8 }}>
              You are responsible for managing your own API keys, usage limits, and billing with each provider. Narrator stores API keys locally on your device and does not transmit them to any server other than the respective provider.
            </p>
          </Section>

          <Section title="Analytics">
            <p>
              Narrator collects anonymous usage analytics by default to help improve the application. No personally identifiable information is collected. You can opt out at any time in Settings. See our <strong style={{ color: colors.text.primary }}>Privacy Policy</strong> for details.
            </p>
          </Section>

          <Section title="Data Ownership">
            <p>
              All projects, videos, scripts, and configuration remain on your local device. Narrator does not upload, store, or process your content on any server. You retain full ownership of all content you create with Narrator.
            </p>
          </Section>

          <Section title="Changes to Terms">
            <p>
              These terms may be updated from time to time. Changes will be reflected in the app and on our GitHub repository. Continued use of Narrator after changes constitutes acceptance of the updated terms.
            </p>
          </Section>
        </div>

        <div style={{ marginTop: 16, display: "flex", justifyContent: "flex-end", flexShrink: 0 }}>
          <Button variant="secondary" onClick={onClose}>Done</Button>
        </div>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 20 }}>
      <h3 style={{ ...typography.sectionLabel, color: colors.accent.primary, marginBottom: 8 }}>{title}</h3>
      {children}
    </div>
  );
}
